name: TeleportOffset
version: '${project.version}'
main: org.windy.teleportoffset.TeleportOffset
api-version: '1.20'
commands:
  teleportoffset:
    description: Commands for TeleportOffset plugin.
    usage: /<command> [reload]


